### Login request
POST http://lb-2b9fba17.elb.localhost.localstack.cloud:4004/auth/login
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "password123"
}

> {% client.global.set("token", response.body.token) %}